export {default as AboutUs} from './AboutUs/AboutUs';
export {default as Chef} from './Chef/Chef';
export {default as FindUs} from './FindUs/FindUs';
export {default as Footer} from './Footer/Footer';
export {default as Gallery} from './Gallery/Gallery';
export {default as Header} from './Header/Header';
export {default as Intro} from './Intro/Intro';
export {default as Laurels} from './Laurels/Laurels';
export {default as Menu} from './Menu/Menu';